version: "3.7"

networks:
  maild:

volumes:
  # mail storage
  vmail:
  spool:
  # certs storage
  certs:
  # AV storage
  clamav:
  # filtering storage
  amavis:
  spamassassin:
  # database storage
  db:


services:
  db:
    image: postgres:latest
    container_name: maild-db
    hostname: db
    env_file:
      - vars/db.env
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - maild

  admin:
    image: maild/admin
    build: ./admin/
    container_name: maild-admin
    hostname: admin
    ports:
      - "8080:80"
    environment:
      POSTFIXADMIN_DB_PASSWORD: ${POSTGRES_PASSWORD}
      POSTFIXADMIN_SETUP_PASSWORD: ${POSTFIXADMIN_SETUP_PASSWORD}
    env_file:
      - vars/db.env
      - vars/admin.env
      - .env
    depends_on:
      - db
    networks:
      - maild
      
  mda:
    image: maild/mda
    build: ./mda/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-mda
    hostname: mda
    env_file:
      - vars/db.env
      - vars/mda.env
      - vars/ssl.env
      - .env
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "4190"
      - "12345"
    depends_on:
      - db
    volumes:
      - vmail:/home/vmail
      - certs:/certs
      - spool:/var/spool/
    networks:
      - maild

  # mta:
  #   # TODO: Healthcheck:
  #   #  - check if $AMAVISIP still has the same IP, if not reboot
  #   #  - check if 
  #   image: mailad/mta
  #   build: ./mta/
  #   container_name: maild-mta
  #   domainname: ${DEFAULT_DOMAIN}
  #   hostname: mta
  #   environment:
  #     MAILADMIN: ${MAIL_ADMIN_USER}@${DEFAULT_DOMAIN}
  #   env_file:
  #     - vars/mta.env
  #     - vars/ssl.env
  #   ports:
  #     - "25:25"
  #     - "465:465"
  #     - "587:587"
  #     - "10025:10025"
  #   networks:
  #     - maild
  #   volumes:
  #     - vmail:/home/vmail
  #     - certs:/certs

  # clamav:
  #   image: mailad/clamav
  #   build: ./clamav/
  #   domainname: ${DOMAIN}
  #   hostname: clamav
  #   healthcheck:
  #       test: ["CMD", "./check.sh"]
  #       interval: 60s
  #       retries: 3
  #       start_period: 120s
  #   environment:
  #     # CLAMAV_PROXY_SERVER: 10.1.2.3
  #     # CLAMAV_PROXY_PORT: 3128
  #     CLAMAV_ALTERNATE_MIRROR: clamav.ddns.net
  #   ports:
  #     - "3310"
  #   volumes:
  #     - clamav:/var/lib/clamav

  # amavis:
  #   image: mailad/amavis
  #   build: ./amavis/
  #   domainname: ${DOMAIN}
  #   hostname: amavis
  #   healthcheck:
  #       test: ["CMD", "/check.sh"]
  #       interval: 60s
  #       retries: 3
  #       start_period: 120s
  #   environment:
  #     AMAVIS_MTA: mta
  #     AMAVIS_SPAMASSASSIN_DISABLED: 1
  #     AMAVIS_AV_DISABLED: 1
  #   ports:
  #     - "10024:10024"
  #   volumes:
  #     - amavis:/var/lib/amavis
  #     - spamassassin:/var/lib/spamassassin
