networks:
  maild:
    external: true

volumes:
  openldap:
  slapd:
  certs:
  vmail: # mail storage
  spool: # temp mail storage
  clamav: # AV storage 
  amavis: # filtering storage
  spamassassin: # spam data 


services:
  cron:
    image: pavelmc/maild_cron:latest
    build: ./cron/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-cron
    hostname: cron
    restart: always
    env_file:
      - vars/amavis.env
      - .env
    volumes:
      - /var/log:/var/log
      - vmail:/home/vmail
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  openldap:
    image: adrianrp1988/openldap:latest
    build: ./openldap/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-openldap
    restart: always
    hostname: openldap
    volumes:
      - openldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
      - certs:/container/service/slapd/assets/certs
    env_file:
      - vars/openldap.env
      - .env
    environment:
      - LDAP_DOMAIN=${DEFAULT_DOMAIN}
    ports:
      - 389:389/tcp
    networks:
      - maild
  openldap-admin:
    image: wheelybird/luminary:latest
    container_name: openldap-admin
    env_file:
      - vars/openldap-ui.env
      - .env
    environment:
      - EMAIL_DOMAIN=${DEFAULT_DOMAIN}
      - LDAP_ADMIN_BIND_DN=cn=admin,${LDAP_BASE_DN}
      - LDAP_ADMIN_BIND_PWD=${LDAP_ADMIN_PASSWORD}
    depends_on:
      - openldap
    ports:
      - 8080:80
      - 8443:443
    networks:
      - maild

  clamav:
    image: pavelmc/maild_clamav:latest
    build: ./clamav/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-clamav
    hostname: clamav
    restart: always
    # healthcheck:  # buiilt in the image
    #   test: [ "CMD", "./check.sh" ]
    #   interval: 60s
    #   retries: 3
    #   start_period: 120s
    env_file:
      - vars/clamav.env
    # ports:
    #   - "3310"
    volumes:
      - clamav:/var/lib/clamav
      - amavis:/var/lib/amavis
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  

  amavis:
    image: pavelmc/maild_amavis:latest
    build: ./amavis/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-amavis
    hostname: amavis
    restart: always
    # ports:
    #   - "8060:80"
    env_file:
      - vars/amavis.env
      - vars/mua.env
      - .env
    depends_on:
      - mda
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  mda:
    image: pavelmc/maild_mda:latest
    build: ./mda/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-mda
    hostname: mda
    restart: always
    env_file:
      - vars/openldap.env
      - vars/mda.env
      - vars/ssl.env
      - .env
    ports:
      # - "110:110"
      # - "143:143"
      - "993:993"
      - "995:995"
      # - "4190"
      # - "12345"
    depends_on:
      - openldap
    volumes:
      - vmail:/home/vmail
      - /certs:/certs
      - spool:/var/spool/
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  mta:
    image: pavelmc/maild_mta:latest
    build: ./mta/
    container_name: maild-mta
    domainname: ${DEFAULT_DOMAIN}
    hostname: mta
    restart: always
    environment:
      MAILADMIN: ${MAIL_ADMIN_USER}@${DEFAULT_DOMAIN}
      DEBUG: 'true'
    env_file:
      - vars/mta.env
      - vars/ssl.env
      - vars/openldap.env
      - .env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - vmail:/home/vmail
      - /certs:/certs
      - spool:/var/spool/
    depends_on:
      - openldap
      - mda
      - amavis
      - clamav
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  mua:
    image: pavelmc/maild_mua:latest
    build: ./mua/
    container_name: maild-mua
    hostname: mua
    restart: always
    env_file:
      - vars/openldap.env
      - vars/amavis.env
      - .env
    volumes:
      - /var/log:/var/log
      - vmail:/home/vmail
    depends_on:
      - openldap
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
