version: "3.7"

networks:
  maild:

volumes:
  # mail storage
  vmail:
  spool:
  # certs storage
  certs:
  # AV storage
  clamav:
  # filtering storage
  amavis:
  spamassassin:
  # database storage
  db:


services:
  db:
    image: postgres:latest
    container_name: maild-db
    environment:
      &db_vars
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - maild

  admin:
    image: postfixadmin:latest
    container_name: maild-admin
    ports:
      - "8080:80"
    environment:
      # db
      POSTFIXADMIN_DB_HOST: ${PG_HOST}
      POSTFIXADMIN_DB_USER: ${PG_USER}
      POSTFIXADMIN_DB_PASSWORD: ${PG_PASSWD}
      POSTFIXADMIN_DB_NAME: ${PG_DB}
      # specific ones
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_SMTP_SERVER: mta
      POSTFIXADMIN_SMTP_PORT: 25
      POSTFIXADMIN_SETUP_PASSWORD: ${POSTFIXADMIN_SETUP_PASSWORD}
    depends_on:
      - db
    networks:
      - maild
      
  mda:
    image: maild/mda
    build: ./mda/
    domainname: ${DOMAIN}
    container_name: maild-mda
    hostname: mda
    environment:
      <<: *db_vars
      # Domain
      DOMAIN: ${DOMAIN}
      DOVECOT_DEFAULT_MAILBOX_SIZE: ${DEFAULT_MAILBOX_SIZE}
      # cert generation
      COUNTRY: ${COUNTRY}
      STATE: ${STATE}
      CITY: ${CITY}
      ORG: ${ORG}
      OU: ${OU}
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "4190"
      - "12345"
    depends_on:
      - db
    volumes:
      - vmail:/home/vmail
      - certs:/certs
      - spool:/var/spool/
    networks:
      - maild

  # mta:
  #   image: mailad/mta
  #   build: ./mta/
  #   domainname: ${DOMAIN}
  #   hostname: mta
  #   environment:
  #     # POSTFIX_MAX_MESSAGESIZE: 2264924 # bytes ~1024 * 1024 * MB * 1.08
  #     # POSTFIX_REALY: 
  #     # POSTFIX_ALWAYS_BCC: piler@${DOMAIN}
  #     # POSTFIX_NATIONAL: cu
  #     # POSTFIX_EVERYONE: todos@${DOMAIN} # if not explicit: disabled
  #     # POSTFIX_SPF_ENABLE: True
  #     # POSTFIX_DNSBL: True
  #     POSTFIX_DOMAIN: ${DOMAIN}
  #     POSTFIX_MAILADMIN: ${MAIL_ADMIN_USER}@${DOMAIN}
  #     POSTFIX_LDAP_URI: "ldap://dc:389"
  #     POSTFIX_LDAP_SEARCH_BASE: ${LDAP_USER_SEARCH_BASE}
  #     POSTFIX_LDAP_BINDUSER: ${SAMBA_LINK_USER_CN}
  #     POSTFIX_LDAP_BINDUSER_PASSWD: ${SAMBA_LINK_USER_PASSWD}
  #     POSTFIX_AMAVIS: amavis
  #   ports:
  #     - "25:25"
  #     - "465:465"
  #     - "587:587"
  #     - "10025:10025"
  #   volumes:
  #     - vmail:/home/vmail
  #     - certs:/certs

  # clamav:
  #   image: mailad/clamav
  #   build: ./clamav/
  #   domainname: ${DOMAIN}
  #   hostname: clamav
  #   healthcheck:
  #       test: ["CMD", "./check.sh"]
  #       interval: 60s
  #       retries: 3
  #       start_period: 120s
  #   environment:
  #     # CLAMAV_PROXY_SERVER: 10.1.2.3
  #     # CLAMAV_PROXY_PORT: 3128
  #     CLAMAV_ALTERNATE_MIRROR: clamav.ddns.net
  #   ports:
  #     - "3310"
  #   volumes:
  #     - clamav:/var/lib/clamav

  # amavis:
  #   image: mailad/amavis
  #   build: ./amavis/
  #   domainname: ${DOMAIN}
  #   hostname: amavis
  #   healthcheck:
  #       test: ["CMD", "/check.sh"]
  #       interval: 60s
  #       retries: 3
  #       start_period: 120s
  #   environment:
  #     AMAVIS_MTA: mta
  #     AMAVIS_SPAMASSASSIN_DISABLED: 1
  #     AMAVIS_AV_DISABLED: 1
  #   ports:
  #     - "10024:10024"
  #   volumes:
  #     - amavis:/var/lib/amavis
  #     - spamassassin:/var/lib/spamassassin
